import React from 'react'
import {
  Award,
  AlertCircle,
  BookOpen,
  Brain,
  Calendar,
  Camera,
  Cat,
  Clock,
  Coffee,
  Crown,
  Feather,
  FileText,
  Flame,
  Gift,
  Handshake,
  Heart,
  HeartCrack,
  HeartHandshake,
  HelpCircle,
  Home,
  ImagePlus,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  Medal,
  MessageCircle,
  MessageSquare,
  Moon,
  RotateCcw,
  Scale,
  Shield,
  ShoppingBag,
  Star,
  Target,
  Trophy,
  TrendingUp,
  User,
  Zap,
  Eye
} from 'lucide-react'

const EMOJI_ICON_MAP = {
  '🐾': Cat,
  '🐱': Cat,
  '😺': Cat,
  '😻': Cat,
  '😿': Cat,
  '😾': Cat,
  '🙀': Cat,
  '😽': Cat,
  '👑': Crown,
  '🔥': Flame,
  '💎': Award,
  '🌟': Star,
  '✨': Star,
  '💫': Star,
  '⭐': Star,
  '⚖️': Scale,
  '☀️': Zap,
  '🌙': Moon,
  '☽': Moon,
  '😴': Moon,
  '💤': Moon,
  '📖': BookOpen,
  '📜': FileText,
  '🗂️': FileText,
  '📸': Camera,
  '🖼️': ImagePlus,
  '🏆': Trophy,
  '📅': Calendar,
  '🔒': Lock,
  '🔐': Lock,
  '🔓': Lock,
  '🔑': Shield,
  '📧': Mail,
  '👁️': Eye,
  '💡': Lightbulb,
  '⏳': Clock,
  '⏰': Clock,
  '🔄': RotateCcw,
  '🤝': Handshake,
  '🤲': HeartHandshake,
  '💬': MessageCircle,
  '💕': Heart,
  '❤️': Heart,
  '💗': Heart,
  '💖': Heart,
  '😍': Heart,
  '🥰': Heart,
  '😂': MessageCircle,
  '🤍': Heart,
  '💛': Heart,
  '💑': HeartHandshake,
  '💔': HeartCrack,
  '🪙': Medal,
  '🎁': Gift,
  '🎀': Gift,
  '🎂': Gift,
  '🎉': Star,
  '🎊': Star,
  '🎈': Star,
  '🕯️': Lightbulb,
  '🥂': Coffee,
  '☕': Coffee,
  '🏡': Home,
  '🏪': ShoppingBag,
  '🍽️': Coffee,
  '👨‍🍳': Coffee,
  '🥞': Coffee,
  '🍰': Coffee,
  '🍕': Coffee,
  '🛁': Home,
  '🎬': Eye,
  '🎯': Target,
  '🎮': Target,
  '🎵': MessageSquare,
  '🎨': Feather,
  '🌈': Star,
  '⚽': Trophy,
  '🛋️': Home,
  '💪': TrendingUp,
  '🛍️': ShoppingBag,
  '🚗': TrendingUp,
  '📺': Eye,
  '💆': HeartHandshake,
  '🤗': HeartHandshake,
  '🧹': Feather,
  '🗣️': MessageCircle,
  '🧠': Brain,
  '📊': TrendingUp,
  '🐢': User,
  '✍️': Feather,
  '🏃': TrendingUp,
  '🌲': Leaf,
  '✈️': TrendingUp,
  '📱': MessageCircle,
  '🤐': MessageSquare,
  '🤔': HelpCircle,
  '😶': User,
  '😬': AlertCircle,
  '🤫': MessageSquare,
  '📢': MessageCircle,
  '💌': Mail,
  '😊': Heart,
  '🦶': TrendingUp,
  '🦃': Star,
  '🎄': Star,
  '🎅': User,
  '🧧': Gift,
  '🏮': Lightbulb,
  '🥮': Coffee,
  '🛒': ShoppingBag,
  '🌸': Leaf,
  '💐': Leaf
}

const EmojiIcon = ({ emoji, className }) => {
  const Icon = EMOJI_ICON_MAP[emoji] || HelpCircle
  return <Icon className={className} aria-hidden="true" />
}

export default EmojiIcon
