-- ============================================
-- ABUSE TELEMETRY FOUNDATION
-- ============================================
-- Adds:
-- - ai_usage_events: token/cost telemetry for AI provider calls
-- - abuse_actions: moderation/abuse actions linked to telemetry events

CREATE TABLE IF NOT EXISTS ai_usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source TEXT NOT NULL,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    input_tokens INTEGER NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
    output_tokens INTEGER NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
    total_tokens INTEGER NOT NULL DEFAULT 0 CHECK (total_tokens >= 0),
    estimated_cost_usd NUMERIC(12, 8) NOT NULL DEFAULT 0 CHECK (estimated_cost_usd >= 0),
    raw_usage JSONB NOT NULL DEFAULT '{}'::JSONB,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE INDEX IF NOT EXISTS idx_ai_usage_events_created_at
    ON ai_usage_events (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_usage_events_user_created
    ON ai_usage_events (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ai_usage_events_model_created
    ON ai_usage_events (model, created_at DESC);

CREATE TABLE IF NOT EXISTS abuse_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ai_usage_event_id BIGINT REFERENCES ai_usage_events(id) ON DELETE SET NULL,
    user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    reason TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE INDEX IF NOT EXISTS idx_abuse_actions_created_at
    ON abuse_actions (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_abuse_actions_user_created
    ON abuse_actions (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_abuse_actions_action_created
    ON abuse_actions (action, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_abuse_actions_ai_event
    ON abuse_actions (ai_usage_event_id);

ALTER TABLE ai_usage_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE abuse_actions ENABLE ROW LEVEL SECURITY;
